# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 80ffa511569388bce791e9dde20334241995e1a75b7d0be5e26c1a174021ce4e8ba869dc9d0eddfbf798560b82725030e055327c247c5db4321b0aef6d0dd892

test:
  secret_key_base: c15efa5d6183c36bd2ba8a7ab0303add2b2fed03a648ef7511f23e07278f83ea328d74d2a5c748431936d5e690a88f2ef54289b7d91b895ae68a31244fb25b8b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
